version: '3.8'
services:
  web:
    build:
      context: .
    env_file: .env
    container_name: client_tcc
    restart: unless-stopped
    volumes:
      - ./app:/srv/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}

volumes:
  client-tcc-data: